package kimistatus

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PatchScript generates a Python sitecustomize script that monkey-patches
// Kimi's bottom toolbar to display XiT status. This is EXPERIMENTAL and
// generated as a dry-run artifact — it is NOT applied automatically.
func PatchScript(xitHome string) string {
	return fmt.Sprintf(`# XiT Kimi Bottom Toolbar Monkey Patch — EXPERIMENTAL
# Generated by xit kimi status-prototype --dry-run-patch
#
# WARNING: This patch modifies Kimi's internal UI behavior. It may break on
# Kimi updates, corrupt the TUI, or cause crashes. Use at your own risk.
#
# To test (NOT recommended for daily use):
#   1. Locate your Kimi Python environment's site-packages directory.
#   2. Save this file as sitecustomize.py in that directory.
#   3. Restart Kimi.
#   4. If Kimi crashes, remove sitecustomize.py immediately.
#
# This patch is NOT installed by XiT automatically.

import os
import time

_XIT_HOME = %q
_XIT_STATUS_FILE = os.path.join(_XIT_HOME, "kimi-hooks", "status.txt")


def _xit_read_status():
    try:
        with open(_XIT_STATUS_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    except Exception:
        return None


def _xit_patch_bottom_toolbar():
    try:
        from kimi_cli.ui.shell import prompt as _prompt_module
    except Exception:
        return

    original_render = None
    if hasattr(_prompt_module, "ShellPrompt"):
        cls = _prompt_module.ShellPrompt
        if hasattr(cls, "_render_bottom_toolbar"):
            original_render = cls._render_bottom_toolbar

    if original_render is None:
        return

    def _patched_render(self):
        # Call original to get base FormattedText
        result = original_render(self)
        fragments = list(result)

        # Try to append XiT status as a trailing fragment before the right span.
        status = _xit_read_status()
        if status:
            # Insert a small XiT badge near the end if there is room.
            # This is a fragile heuristic; real implementation would need
            # column-aware layout.
            xit_fragment = ("class:bottom-toolbar", "  [XiT: " + status + "]")
            # Insert before the final right-aligned span (typically the last fragment).
            if len(fragments) > 2:
                fragments.insert(len(fragments) - 1, xit_fragment)
            else:
                fragments.append(xit_fragment)

        from prompt_toolkit.formatted_text import FormattedText
        return FormattedText(fragments)

    cls._render_bottom_toolbar = _patched_render


_xit_patch_bottom_toolbar()
`, xitHome)
}

// WritePatchScript writes the patch script to the given path.
func WritePatchScript(xitHome, outPath string) error {
	script := PatchScript(xitHome)
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(script), 0644)
}

// DefaultPatchPath returns the default path for the dry-run patch script.
func DefaultPatchPath(home string) string {
	return filepath.Join(home, "kimi-hooks", "status_bar_patch.py")
}

// TitleFromStatus generates a compact terminal title string from XiT stats.
func TitleFromStatus(observed, rerouted, saved int) string {
	parts := []string{"XiT"}
	if observed > 0 {
		parts = append(parts, fmt.Sprintf("observed %d", observed))
	}
	if rerouted > 0 {
		parts = append(parts, fmt.Sprintf("auto %d", rerouted))
	}
	if saved > 0 {
		parts = append(parts, fmt.Sprintf("saved ~%d", saved))
	}
	return strings.Join(parts, " ")
}

// StatusTextFromStats builds a short status string for title or toast.
func StatusTextFromStats(observed, rerouted int) string {
	if rerouted > 0 {
		return fmt.Sprintf("obs %d | auto %d", observed, rerouted)
	}
	if observed > 0 {
		return fmt.Sprintf("obs %d", observed)
	}
	return "active"
}
